### ISSUE TITLE
[Design] 是否应该把 ABT Node  Blocklet 相关的文档添加到首页

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/www-docs#35]
![image](https://user-images.githubusercontent.com/719985/100853579-e67a3300-34c2-11eb-84ab-f90835fec3a5.png)

现在的文档首页有些过时，并且不能反映平台包括的产品和能力，文档站应该围绕我们最重要的三款产品去组织：

- Blockchain Framework
	- [ ] Forge CLI
	- [ ] Forge Docs
- ABT Wallet & DID
	- [ ] DID-Auth Library，hold
	- [ ] DID-Auth Protocol，hold
	- [ ] Wallet SDK
	- [ ] DID SDK
- ABT Node & Blocklets
	- [ ] ABT Node User Guide
	- [ ] Blocklet Meta Spec
	- [ ] Blocklet Dev Guide

@mave99a 你有什么建议？

**Comment by wangshijun** [comment]
ok，那我们 docs 的首页也直接显示 developer portal？

**Comment by mave99a** [comment]
> ok，那我们 docs 的首页也直接显示 developer portal？

docs的首页可以先redirect给 developer 页面？

**Comment by Jeanchen27** [comment]
developer 页面和 docs 页面理应合并，保持简单。

**Comment by mave99a** [comment]
no longer valid.
